theme: jekyll-theme-midnight
title: <img src="https://media.discordapp.net/attachments/806343355264401478/820076457690398751/GBG-team-logo-125.png?width=90&height=90" alt="Gas Brake Go">
description: Team Info
markdown: kramdown
