theme: jekyll-theme-midnight
title: <img src="https://media.discordapp.net/attachments/806343355264401478/820076457690398751/GBG-team-logo-125.png" alt="Gas Brake Go">
markdown: kramdown
google_analytics: G-J72GG1JKW1
timezone: America/New_York

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    measurement_id          : "G-J72GG1JKW1"
    anonymize_ip         : # true, false (default)
